/**
 * Portal admin — managed artwork.
 *
 * Images uploaded here are stored outside Git (`modules/artworkAssets`) and
 * referenced from authored content by id. Shipped artwork under `assets/` is
 * a separate thing these routes never touch.
 *
 *   - `artwork.read`  — list, get (with references and history), the bytes,
 *     the upload limits, and the scene preview.
 *   - `artwork.write` — upload, replace, rename / re-categorise,
 *     disable / enable, delete.
 *
 * An enemy's artwork is set on the enemy itself (`admin/enemies.ts`); these
 * routes only hold the images it points at.
 *
 * ## Uploads
 *
 * The body **is** the file: `POST /admin/artwork/assets?category=…` with the
 * raw bytes, not a multipart form. The cookie session's CSRF check
 * (`registerAuth`) applies as to every other write. Nothing the client says
 * about the file is trusted: the declared `Content-Type` only selects the
 * parser, the type is read from the bytes, the stored name is generated by
 * the server, and `filename` is kept as a label after being reduced to a base
 * name. The route's body limit is the upload ceiling; a larger file is 413.
 *
 * ## Serving
 *
 * Bytes are served with the stored MIME type, `nosniff`, a sandboxing CSP and
 * an `ETag` of the content hash. A URL carrying the current hash
 * (`?v=<hash>`) is immutable; replacing the asset changes the hash, so no
 * client keeps showing the old image.
 */
import { readFile } from 'node:fs/promises';
import { z } from 'zod';
import type { FastifyReply, FastifyRequest } from 'fastify';
import type { ApiContext } from '../../../context';
import type { FastifyPluginAsyncZod } from '../../../plugins/typeProvider';
import { dataSchema, ok } from '../../../plugins/responseEnvelope';
import { commonErrorResponses, errorSchema, notFoundResponse } from '../../../schemas/common';
import { requirePortalPermission } from '../../../plugins/portalPermissions';
import { ApiErrorWithDetails } from '../../../errors';
import { ARTWORK_ASSET_CATEGORIES, ARTWORK_ASSET_STATUSES } from '../../../../db/schema';
import {
  ARTWORK_ASSET_LIST_MAX_LIMIT,
  ARTWORK_ASSET_NAME_MAX_LENGTH,
  type ArtworkAsset,
  type ArtworkAssetService,
} from '../../../../modules/artworkAssets/artworkAssetService';
import {
  ARTWORK_MAX_DIMENSION,
  ARTWORK_UPLOAD_MAX_BYTES,
} from '../../../../modules/artworkAssets/imageInspection';
import { playerBuddySpriteLayer, resolveArtworkLayer } from '../../../../modules/artworkAssets/sceneLayers';
import {
  PLAYER_BUDDY_COLLISION_SHARE,
  SCENE_HEIGHT,
  SCENE_WIDTH,
  layoutOverlapShare,
  mirrorsPlayerBuddy,
  SPRITE_ANCHORS,
  SPRITE_OFFSET_X_MAX,
  SPRITE_OFFSET_Y_MAX,
  SPRITE_SCALE_MAX_BP,
  SPRITE_SCALE_MIN_BP,
  SpritePlacementSchema,
} from '../../../../modules/artworkAssets/scenePlacement';
import { ARTWORK_PATH_MAX_LENGTH } from '../../../../modules/assets/artworkPath';
import { AppError, ArtworkAssetInUseError } from '../../../../shared/errors';

const UPLOAD_CONTENT_TYPES = ['image/png', 'image/webp', 'image/jpeg', 'application/octet-stream'];

const idParams = z.object({ id: z.string().uuid() });
const categorySchema = z.enum(ARTWORK_ASSET_CATEGORIES);

const assetSchema = z.object({
  id: z.string(),
  category: categorySchema,
  name: z.string(),
  originalFilename: z.string(),
  mimeType: z.string(),
  width: z.number().int(),
  height: z.number().int(),
  hasAlpha: z.boolean(),
  fileSize: z.number().int(),
  contentHash: z.string(),
  version: z.number().int(),
  status: z.enum(ARTWORK_ASSET_STATUSES),
  uploadedBy: z.string().nullable(),
  updatedBy: z.string().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
  replacedAt: z.string().nullable(),
});

const referenceSchema = z.object({
  kind: z.enum(['dungeon_zone', 'combat_enemy', 'boss']),
  key: z.string(),
  name: z.string().nullable(),
  field: z.string(),
});

const eventSchema = z.object({
  id: z.number().int(),
  action: z.string(),
  actor: z.string().nullable(),
  oldHash: z.string().nullable(),
  newHash: z.string().nullable(),
  details: z.record(z.string(), z.unknown()),
  createdAt: z.string(),
});

/** A scene layer named by a managed asset, a shipped path, or both (the asset wins). */
const layerRefSchema = z
  .object({
    assetId: z.string().uuid().nullable().optional(),
    artworkPath: z.string().min(1).max(ARTWORK_PATH_MAX_LENGTH).nullable().optional(),
  })
  .strict();

function toAsset(a: ArtworkAsset): z.infer<typeof assetSchema> {
  return {
    ...a,
    createdAt: a.createdAt.toISOString(),
    updatedAt: a.updatedAt.toISOString(),
    replacedAt: a.replacedAt?.toISOString() ?? null,
  };
}

/** Reply shape for a binary body; the zod provider only types JSON replies. */
type BinaryReply = {
  code(status: number): BinaryReply;
  header(k: string, v: string): BinaryReply;
  send(payload?: Buffer): unknown;
};

/** Headers every served image carries: it is data, never a document. */
function imageHeaders(reply: FastifyReply, contentType: string): BinaryReply {
  return (reply as unknown as BinaryReply)
    .header('content-type', contentType)
    .header('x-content-type-options', 'nosniff')
    .header('content-security-policy', "default-src 'none'; sandbox")
    .header('cross-origin-resource-policy', 'same-origin');
}

async function translate<T>(work: () => Promise<T>): Promise<T> {
  try {
    return await work();
  } catch (err) {
    if (err instanceof ArtworkAssetInUseError) {
      throw new ApiErrorWithDetails(err.code, err.message, err.userMessage, { references: err.references });
    }
    throw err;
  }
}

export const adminArtworkAssetRoutes =
  (ctx: ApiContext): FastifyPluginAsyncZod =>
  async (app) => {
    const service = ctx.services.artworkAssets;
    const authorization = ctx.portalAuthorization;
    if (!service) return;
    const assets: ArtworkAssetService = service;
    const scenes = ctx.services.sceneComposition;
    const assetsDir = ctx.assetsDir ?? './assets';

    // The upload body is the file. Scoped to this plugin: no other route
    // accepts a binary body.
    app.addContentTypeParser(UPLOAD_CONTENT_TYPES, { parseAs: 'buffer' }, (_req, body, done) => done(null, body));

    const gate =
      (permission: 'artwork.read' | 'artwork.write') =>
      async (req: FastifyRequest): Promise<void> => {
        if (!authorization) {
          throw new AppError(
            'PORTAL_PERMISSION_DENIED',
            'Portal authorization service is not configured',
            'Admin features are unavailable.',
          );
        }
        await requirePortalPermission(req, authorization, permission, {
          allowBearer: ctx.adminBearerAllowed === true,
        });
      };

    const notFound = (id: string) => new AppError('NOT_FOUND', `Artwork asset ${id} not found`, 'Not found.');
    const actorOf = (req: FastifyRequest) => req.portalSession?.discordUserId ?? null;
    const uploadBody = (req: FastifyRequest): Buffer => {
      if (!Buffer.isBuffer(req.body) || req.body.length === 0) {
        throw new AppError(
          'VALIDATION_ERROR',
          'Upload body missing',
          'Send the image as the request body, with an image Content-Type.',
        );
      }
      return req.body;
    };
    const tags = ['Admin — Artwork'];
    const uploadLimit = { bodyLimit: ARTWORK_UPLOAD_MAX_BYTES };

    app.get(
      '/admin/artwork/meta',
      {
        preValidation: gate('artwork.read'),
        schema: {
          tags,
          summary: 'Upload limits, categories, and the scene size and placement bounds',
          response: {
            200: dataSchema(
              z.object({
                categories: z.array(categorySchema),
                mimeTypes: z.array(z.string()),
                maxBytes: z.number().int(),
                maxDimension: z.number().int(),
                scene: z.object({ width: z.number().int(), height: z.number().int() }),
                placement: z.object({
                  anchors: z.array(z.string()),
                  scaleMin: z.number().int(),
                  scaleMax: z.number().int(),
                  offsetXMax: z.number().int(),
                  offsetYMax: z.number().int(),
                }),
              }),
            ),
            ...commonErrorResponses,
          },
        },
      },
      async (req) =>
        ok(req, {
          categories: [...ARTWORK_ASSET_CATEGORIES],
          mimeTypes: ['image/png', 'image/webp', 'image/jpeg'],
          maxBytes: ARTWORK_UPLOAD_MAX_BYTES,
          maxDimension: ARTWORK_MAX_DIMENSION,
          scene: { width: SCENE_WIDTH, height: SCENE_HEIGHT },
          placement: {
            anchors: [...SPRITE_ANCHORS],
            scaleMin: SPRITE_SCALE_MIN_BP,
            scaleMax: SPRITE_SCALE_MAX_BP,
            offsetXMax: SPRITE_OFFSET_X_MAX,
            offsetYMax: SPRITE_OFFSET_Y_MAX,
          },
        }),
    );

    app.get(
      '/admin/artwork/assets',
      {
        preValidation: gate('artwork.read'),
        schema: {
          tags,
          summary: 'List managed artwork, newest first. Filter by category and status; search by name or file name',
          querystring: z.object({
            category: categorySchema.optional(),
            status: z.enum(['active', 'disabled']).optional(),
            q: z.string().max(100).optional(),
            limit: z.coerce.number().int().min(1).max(ARTWORK_ASSET_LIST_MAX_LIMIT).optional(),
            offset: z.coerce.number().int().min(0).optional(),
          }),
          response: {
            200: dataSchema(z.object({ assets: z.array(assetSchema), total: z.number().int() })),
            ...commonErrorResponses,
          },
        },
      },
      async (req) => {
        const { q, ...rest } = req.query;
        const { assets: rows, total } = await assets.list({ ...rest, search: q });
        return ok(req, { assets: rows.map(toAsset), total });
      },
    );

    app.get(
      '/admin/artwork/assets/:id',
      {
        preValidation: gate('artwork.read'),
        schema: {
          tags,
          summary: 'One asset, with what references it and its change history',
          params: idParams,
          response: {
            200: dataSchema(
              z.object({ asset: assetSchema, references: z.array(referenceSchema), events: z.array(eventSchema) }),
            ),
            ...notFoundResponse,
            ...commonErrorResponses,
          },
        },
      },
      async (req) => {
        const asset = await assets.get(req.params.id);
        if (!asset || asset.status === 'deleted') throw notFound(req.params.id);
        const [references, events] = await Promise.all([assets.references(asset.id), assets.events(asset.id)]);
        return ok(req, {
          asset: toAsset(asset),
          references,
          events: events.map((e) => ({ ...e, createdAt: e.createdAt.toISOString() })),
        });
      },
    );

    app.get(
      '/admin/artwork/assets/:id/file',
      {
        preValidation: gate('artwork.read'),
        schema: {
          tags,
          summary:
            'The image bytes. ETag is the content hash; with `?v=<hash>` naming the current hash the response is immutable',
          params: idParams,
          querystring: z.object({ v: z.string().max(64).optional() }),
          response: { ...notFoundResponse, ...commonErrorResponses },
        },
      },
      async (req, reply) => {
        const found = await assets.read(req.params.id);
        if (!found) throw notFound(req.params.id);
        const etag = `"${found.asset.contentHash}"`;
        const out = imageHeaders(reply, found.asset.mimeType)
          .header('etag', etag)
          .header(
            'cache-control',
            req.query.v === found.asset.contentHash ? 'private, max-age=31536000, immutable' : 'private, no-cache',
          );
        if (req.headers['if-none-match'] === etag) {
          out.code(304).send();
          return reply;
        }
        out.send(found.bytes);
        return reply;
      },
    );

    app.post(
      '/admin/artwork/assets',
      {
        ...uploadLimit,
        preValidation: gate('artwork.write'),
        schema: {
          tags,
          summary:
            'Upload an image (PNG, WebP or JPEG) as the raw request body. The type is read from the bytes; ' +
            '`filename` is kept only as a label',
          querystring: z.object({
            category: categorySchema,
            filename: z.string().max(300).optional(),
            name: z.string().max(ARTWORK_ASSET_NAME_MAX_LENGTH).optional(),
          }),
          response: {
            200: dataSchema(z.object({ asset: assetSchema })),
            413: errorSchema.describe('PAYLOAD_TOO_LARGE — over the upload limit.'),
            ...commonErrorResponses,
          },
        },
      },
      async (req) =>
        ok(req, {
          asset: toAsset(await assets.upload({ bytes: uploadBody(req), ...req.query }, actorOf(req))),
        }),
    );

    app.put(
      '/admin/artwork/assets/:id/file',
      {
        ...uploadLimit,
        preValidation: gate('artwork.write'),
        schema: {
          tags,
          summary:
            'Replace the image behind an asset. The id is kept, so everything referencing it shows the new image; ' +
            'version and hash change',
          params: idParams,
          querystring: z.object({ filename: z.string().max(300).optional() }),
          response: {
            200: dataSchema(z.object({ asset: assetSchema })),
            413: errorSchema.describe('PAYLOAD_TOO_LARGE.'),
            ...notFoundResponse,
            ...commonErrorResponses,
          },
        },
      },
      async (req) => {
        const asset = await assets.replace(
          req.params.id,
          { bytes: uploadBody(req), filename: req.query.filename },
          actorOf(req),
        );
        if (!asset) throw notFound(req.params.id);
        return ok(req, { asset: toAsset(asset) });
      },
    );

    app.patch(
      '/admin/artwork/assets/:id',
      {
        preValidation: gate('artwork.write'),
        schema: {
          tags,
          summary: 'Rename an asset or move it to another category',
          params: idParams,
          body: z
            .object({
              name: z.string().trim().min(1).max(ARTWORK_ASSET_NAME_MAX_LENGTH).optional(),
              category: categorySchema.optional(),
            })
            .strict(),
          response: { 200: dataSchema(z.object({ asset: assetSchema })), ...notFoundResponse, ...commonErrorResponses },
        },
      },
      async (req) => {
        const asset = await assets.update(req.params.id, req.body, actorOf(req));
        if (!asset) throw notFound(req.params.id);
        return ok(req, { asset: toAsset(asset) });
      },
    );

    app.put(
      '/admin/artwork/assets/:id/enabled',
      {
        preValidation: gate('artwork.write'),
        schema: {
          tags,
          summary:
            'Disable or re-enable an asset. Disabling always succeeds: whatever references it falls back to its ' +
            'shipped artwork, and the references are returned so the admin knows what changed',
          params: idParams,
          body: z.object({ enabled: z.boolean() }).strict(),
          response: {
            200: dataSchema(z.object({ asset: assetSchema, references: z.array(referenceSchema) })),
            ...notFoundResponse,
            ...commonErrorResponses,
          },
        },
      },
      async (req) => {
        const result = await assets.setEnabled(req.params.id, req.body.enabled, actorOf(req));
        if (!result) throw notFound(req.params.id);
        return ok(req, { asset: toAsset(result.asset), references: result.references });
      },
    );

    app.delete(
      '/admin/artwork/assets/:id',
      {
        preValidation: gate('artwork.write'),
        schema: {
          tags,
          summary:
            'Delete an asset. Refused with 409 ARTWORK_ASSET_IN_USE (details.references) while anything references it',
          params: idParams,
          response: {
            200: dataSchema(z.object({ deleted: z.literal(true) })),
            409: errorSchema.describe('ARTWORK_ASSET_IN_USE — clear the references in details.references first.'),
            ...notFoundResponse,
            ...commonErrorResponses,
          },
        },
      },
      async (req) => {
        const asset = await translate(() => assets.delete(req.params.id, actorOf(req)));
        if (!asset) throw notFound(req.params.id);
        return ok(req, { deleted: true as const });
      },
    );

    if (scenes) {
      app.post(
        '/admin/artwork/scene-preview',
        {
          preValidation: gate('artwork.read'),
          schema: {
            tags,
            summary:
              'Compose a background and (optionally) a sprite exactly as a player screen would, and return the ' +
              'image. Persists nothing but the render cache. With `playerBuddy`, a Buddy is drawn in the reserved ' +
              'player side as a fight shows her (the named species, else a stand-in), and the ' +
              '`x-scene-player-buddy*` headers report who was drawn and how much of her the enemy sprite covers',
            body: z
              .object({
                background: layerRefSchema,
                sprite: layerRefSchema.nullable().optional(),
                placement: SpritePlacementSchema.optional(),
                playerBuddy: z
                  .object({ speciesSlug: z.string().regex(/^[a-z0-9_]+$/).max(100).optional() })
                  .strict()
                  .nullable()
                  .optional(),
              })
              .strict(),
            response: { ...notFoundResponse, ...commonErrorResponses },
          },
        },
        async (req, reply) => {
          // A preview may show a disabled asset: the admin is deciding about it.
          const resolve = (ref: z.infer<typeof layerRefSchema>) =>
            resolveArtworkLayer({ assets, assetsDir }, ref, { includeDisabled: true });
          const background = await resolve(req.body.background);
          if (!background) {
            throw new AppError('NOT_FOUND', 'Scene background not found', 'That background image is not available.');
          }
          const spriteLayer = req.body.sprite ? await resolve(req.body.sprite) : null;
          if (req.body.sprite && !spriteLayer) {
            throw new AppError('NOT_FOUND', 'Scene sprite not found', 'That sprite image is not available.');
          }
          // The Buddy is never authored: a preview only chooses *whose* sprite stands in
          // for the player's. A species with no sprite just leaves her out, as in a run.
          let playerBuddy: {
            layer: NonNullable<ReturnType<typeof playerBuddySpriteLayer>>;
            mirror: boolean;
            label: string;
          } | null = null;
          if (req.body.playerBuddy) {
            const species = ctx.getContent().species;
            const candidates = req.body.playerBuddy.speciesSlug
              ? [req.body.playerBuddy.speciesSlug]
              : species.map((s) => s.slug).sort();
            for (const slug of candidates) {
              const layer = playerBuddySpriteLayer(assetsDir, slug);
              if (layer) {
                // Mirrored exactly as a run would mirror that species.
                const facing = species.find((s) => s.slug === slug)?.spriteFacing;
                playerBuddy = { layer, mirror: mirrorsPlayerBuddy(facing), label: slug };
                break;
              }
            }
          }
          const request = {
            background,
            sprite: spriteLayer
              ? { layer: spriteLayer, placement: req.body.placement ?? SpritePlacementSchema.parse({}) }
              : null,
            playerBuddy,
          };
          const scene = await scenes.compose(request);
          if (!scene) {
            throw new AppError('VALIDATION_ERROR', 'Scene could not be composed', 'Those images could not be composed.');
          }
          const image = imageHeaders(reply, scene.contentType)
            .header('etag', `"${scene.cacheKey}"`)
            .header('cache-control', 'private, no-cache');
          if (playerBuddy && scene.playerBuddy) {
            const boxes = await scenes.layouts(request);
            const overlap = boxes.playerBuddy && boxes.sprite ? layoutOverlapShare(boxes.playerBuddy, boxes.sprite) : 0;
            image
              .header('x-scene-player-buddy', playerBuddy.label)
              .header('x-scene-player-buddy-overlap', String(Math.round(overlap * 100)))
              .header('x-scene-player-buddy-collision', String(overlap >= PLAYER_BUDDY_COLLISION_SHARE));
          }
          image.send(await readFile(scene.absolutePath));
          return reply;
        },
      );
    }
  };
