/**
 * The storage abstraction, through its local implementation: keys are
 * generated by the server and deterministic, nothing escapes the root, a
 * missing file is an answer rather than an error, and the bytes outlive the
 * object that wrote them. Every test uses its own temp directory.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterAll, describe, expect, it } from 'vitest';
import {
  ArtworkStorageKeyError,
  artworkStorageKey,
  createLocalArtworkStorage,
  isValidArtworkStorageKey,
} from '../../../src/modules/artworkAssets/artworkStorage';

const root = fs.mkdtempSync(path.join(os.tmpdir(), 'wm-artwork-storage-'));
afterAll(() => fs.rmSync(root, { recursive: true, force: true }));

const ID = '3f2b8c1e-9a4d-4e7b-8c1a-2b3c4d5e6f70';
const HASH = 'a'.repeat(64);
const keyOf = (over: Partial<Parameters<typeof artworkStorageKey>[0]> = {}) =>
  artworkStorageKey({ category: 'enemy_sprite', assetId: ID, contentHash: HASH, extension: 'png', ...over });

describe('storage keys', () => {
  it('are deterministic and built only from server-side values', () => {
    expect(keyOf()).toBe(`enemy_sprite/${ID}/${HASH}.png`);
    expect(keyOf()).toBe(keyOf());
    // A replacement (new hash) names a different object under the same asset.
    expect(keyOf({ contentHash: 'b'.repeat(64) })).toBe(`enemy_sprite/${ID}/${'b'.repeat(64)}.png`);
  });

  it('cannot be built from path-like or foreign input', () => {
    for (const bad of [
      { category: '../../etc' },
      { category: 'enemy/sprite' },
      { assetId: '../outside' },
      { assetId: 'not-a-uuid' },
      { contentHash: '../../passwd' },
      { contentHash: 'short' },
      { extension: 'svg' },
      { extension: 'png/../../x' },
      { extension: 'php' },
    ]) {
      expect(() => keyOf(bad), JSON.stringify(bad)).toThrow(ArtworkStorageKeyError);
    }
  });

  it('are validated by shape', () => {
    expect(isValidArtworkStorageKey(keyOf())).toBe(true);
    for (const bad of ['', '/etc/passwd', `enemy_sprite/${ID}/../x.png`, `..\\x`, `enemy_sprite/${ID}/${HASH}.png/extra`, 42, null]) {
      expect(isValidArtworkStorageKey(bad), String(bad)).toBe(false);
    }
  });
});

describe('local storage', () => {
  const storage = createLocalArtworkStorage(path.join(root, 'store'));

  it('stores, reads back and deletes', async () => {
    const key = keyOf();
    expect(await storage.exists(key)).toBe(false);
    await storage.put(key, Buffer.from('image-bytes'));
    expect(await storage.exists(key)).toBe(true);
    expect((await storage.get(key))!.toString()).toBe('image-bytes');
    // No temp file is left behind by the atomic write.
    expect(fs.readdirSync(path.dirname(path.join(root, 'store', ...key.split('/'))))).toEqual([`${HASH}.png`]);
    await storage.delete(key);
    expect(await storage.exists(key)).toBe(false);
  });

  it('answers null for a missing file, and deleting one is not an error', async () => {
    const key = keyOf({ contentHash: 'c'.repeat(64) });
    expect(await storage.get(key)).toBeNull();
    await expect(storage.delete(key)).resolves.toBeUndefined();
  });

  it('refuses every traversal attempt before touching the disk', async () => {
    const outside = path.join(root, 'outside.png');
    fs.writeFileSync(outside, 'secret');
    for (const bad of ['../outside.png', '/etc/passwd', `enemy_sprite/${ID}/../../../outside.png`, `enemy_sprite/../../outside.png`, '']) {
      await expect(storage.get(bad), bad).rejects.toBeInstanceOf(ArtworkStorageKeyError);
      await expect(storage.put(bad, Buffer.from('x')), bad).rejects.toBeInstanceOf(ArtworkStorageKeyError);
      await expect(storage.exists(bad), bad).rejects.toBeInstanceOf(ArtworkStorageKeyError);
      await expect(storage.delete(bad), bad).rejects.toBeInstanceOf(ArtworkStorageKeyError);
    }
    expect(fs.readFileSync(outside, 'utf8')).toBe('secret');
    // Nothing was written anywhere outside the store.
    expect(fs.readdirSync(root).sort()).toEqual(['outside.png', 'store']);
  });

  it('keeps the bytes across a "restart": a new storage over the same root reads them', async () => {
    const dir = path.join(root, 'persistent');
    const key = keyOf({ category: 'dungeon_background', contentHash: 'd'.repeat(64), extension: 'webp' });
    await createLocalArtworkStorage(dir).put(key, Buffer.from('survives'));
    const reopened = createLocalArtworkStorage(dir);
    expect((await reopened.get(key))!.toString()).toBe('survives');
    expect(reopened.description).toContain(dir);
  });
});
