/**
 * Where managed artwork bytes live.
 *
 * {@link ArtworkStorage} is the whole contract the asset service knows: put,
 * read, delete and test by an opaque **storage key**. V1 is a directory on
 * persistent disk ({@link createLocalArtworkStorage}); an S3 / R2 store is
 * another implementation of the same four methods, and nothing above this
 * file changes. The database stores keys, never paths.
 *
 * Keys are generated by the server ({@link artworkStorageKey}) from the asset
 * category, id and content hash — nothing a client typed reaches the
 * filesystem. The local store still validates every key's shape and confines
 * the resolved path to its root, so a row that reached the database some
 * other way cannot read or write outside it.
 */
import { randomBytes } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { isPathInside } from '../assets/assetContainment';

export interface ArtworkStorage {
  /** Human-readable description of the backend, for logs. Never a secret. */
  readonly description: string;
  /** Store `bytes` under `key`, replacing anything already there. */
  put(key: string, bytes: Buffer): Promise<void>;
  /** The bytes under `key`, or null when nothing is stored there. */
  get(key: string): Promise<Buffer | null>;
  exists(key: string): Promise<boolean>;
  /** Remove `key`. Removing a key that is not there is not an error. */
  delete(key: string): Promise<void>;
}

/** Thrown for a key that is not one this server generated. */
export class ArtworkStorageKeyError extends Error {
  constructor(key: string) {
    super(`Invalid artwork storage key: ${JSON.stringify(String(key).slice(0, 80))}`);
    this.name = 'ArtworkStorageKeyError';
  }
}

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const KEY_PATTERN = /^[a-z_]{1,40}\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/[0-9a-f]{64}\.(png|webp|jpg)$/;

/**
 * The storage key for one version of an asset:
 * `<category>/<assetId>/<contentHash>.<ext>`. Deterministic — the same asset
 * and bytes always name the same object — and content-addressed, so a
 * replacement never overwrites the bytes it replaces.
 */
export function artworkStorageKey(input: {
  category: string;
  assetId: string;
  contentHash: string;
  extension: string;
}): string {
  const key = `${input.category}/${input.assetId}/${input.contentHash}.${input.extension}`;
  if (!UUID.test(input.assetId) || !isValidArtworkStorageKey(key)) throw new ArtworkStorageKeyError(key);
  return key;
}

export function isValidArtworkStorageKey(key: unknown): key is string {
  return typeof key === 'string' && KEY_PATTERN.test(key);
}

/** A directory-backed store. `root` is created on first write. */
export function createLocalArtworkStorage(root: string): ArtworkStorage {
  const base = path.resolve(root);

  function locate(key: string): string {
    if (!isValidArtworkStorageKey(key)) throw new ArtworkStorageKeyError(key);
    const resolved = path.resolve(base, ...key.split('/'));
    // The pattern already excludes traversal; this is the second lock.
    if (!isPathInside(base, resolved) || resolved === base) throw new ArtworkStorageKeyError(key);
    return resolved;
  }

  return {
    description: `local directory ${base}`,

    async put(key, bytes) {
      const target = locate(key);
      await fs.mkdir(path.dirname(target), { recursive: true });
      // Write-then-rename: a reader never sees a half-written image.
      const temp = `${target}.${randomBytes(6).toString('hex')}.tmp`;
      try {
        await fs.writeFile(temp, bytes, { mode: 0o644 });
        await fs.rename(temp, target);
      } catch (err) {
        await fs.rm(temp, { force: true });
        throw err;
      }
    },

    async get(key) {
      try {
        return await fs.readFile(locate(key));
      } catch (err) {
        if (err instanceof ArtworkStorageKeyError) throw err;
        if ((err as NodeJS.ErrnoException).code === 'ENOENT' || (err as NodeJS.ErrnoException).code === 'EISDIR') return null;
        throw err;
      }
    },

    async exists(key) {
      try {
        return (await fs.stat(locate(key))).isFile();
      } catch (err) {
        if (err instanceof ArtworkStorageKeyError) throw err;
        return false;
      }
    },

    async delete(key) {
      await fs.rm(locate(key), { force: true });
    },
  };
}
